name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release
    - name: publish
      run: dotnet publish ./src/Lykke.Service.QuorumMonitoring/Lykke.Service.QuorumMonitoring.csproj --output ../../publish --configuration Release
    - name: check
      run: ls ./publish
    - name: check secret
      run: echo ${{ secrets.DOCKER_USERNAME }}
      

